### ISSUE TITLE
Working with the library without connecting to the PlantUML server

### ISSUE THREAD

**Issue by mahdimouatta** [dougn/python-plantuml#16]
Is there a way to work with the library without connecting to the PlantUML server ?

**Comment by uhrwerk** [comment]
You could start a subprocess and call the command prompt and do "java -jar <plantuml.jar> <source.txt>", but you need do download the plantuml jar and have java

`subprocess.run(["java", "-jar", "plantuml.jar", path])
`
That way you would not need this library anymore
