### ISSUE TITLE
plantuml error (non-200 responses) can be either png or html data

### ISSUE THREAD

**Issue by freezed** [dougn/python-plantuml#4]
Hi, what is the reason to not  save the error file with a png extention?

https://github.com/dougn/python-plantuml/blob/f81c51ee73f3ebad9040a2911af0519d1a835811/plantuml.py#L204

**Comment by dougn** [comment]
When there is an error, the text for the error is returned int eh encapsulating html response. That is what is saved to that error file. 
i.e. because it is html, not png.

https://github.com/dougn/python-plantuml/blob/f81c51ee73f3ebad9040a2911af0519d1a835811/plantuml.py#L194-L197

**Comment by dougn** [comment]
It appears that on some errors, the error message on a non 200 response is .png data, not html.

**Comment by dougn** [comment]
We need to check the response content for either a png or html header, and write the error file with the appropriate extension.

**Comment by freezed** [comment]
In which case the response is HTML? I use it for a few weeks only and all errors were PNG.

**Comment by dougn** [comment]
Things have changed in the past 5 years, and now, the errors are often .png data, but can still be html. the correct thing to do is to check the returned data for a png or html header, and write with the appropriate extension.

**Comment by dougn** [comment]
I can no longer reproduce.
